package com.goldbingo.app;

import android.provider.Telephony;
import android.service.notification.NotificationListenerService;
import android.service.notification.StatusBarNotification;

import androidx.work.Constraints;
import androidx.work.Data;
import androidx.work.NetworkType;
import androidx.work.OneTimeWorkRequest;
import androidx.work.WorkManager;


public class PaymentNotificationListener
        extends NotificationListenerService {

    @Override
    public void onNotificationPosted(
            StatusBarNotification sbn
    ) {

        if (sbn == null) {
            return;
        }


        /*
         * Never process GoldBingo's
         * own notifications.
         */
        if (
                getPackageName().equals(
                        sbn.getPackageName()
                )
        ) {
            return;
        }


        /*
         * Only listen to notifications
         * generated by the default SMS app.
         *
         * This prevents WhatsApp,
         * Telegram, email, etc. from
         * being forwarded.
         */
        String defaultSmsPackage =
                Telephony.Sms
                        .getDefaultSmsPackage(
                                this
                        );


        if (
                defaultSmsPackage == null ||
                        !defaultSmsPackage.equals(
                                sbn.getPackageName()
                        )
        ) {
            return;
        }


        android.os.Bundle extras =
                sbn.getNotification()
                        .extras;


        String title =
                extras.getCharSequence(
                        "android.title",
                        ""
                ).toString().trim();


        String text =
                extras.getCharSequence(
                        "android.text",
                        ""
                ).toString().trim();


        String bigText =
                extras.getCharSequence(
                        "android.bigText",
                        ""
                ).toString().trim();


        String message;


        if (!bigText.isEmpty()) {

            message = bigText;

        } else if (!text.isEmpty()) {

            message = text;

        } else {

            return;

        }


        String sender =
                !title.isEmpty()
                        ? title
                        : sbn.getPackageName();
        String normalizedMessage =
                message
                        .replace("\n", " ")
                        .replaceAll("\\s+", " ")
                        .trim();


        String lowerMessage =
                normalizedMessage
                        .toLowerCase();


/* =========================================
   TELEBIRR PAYMENT NOTIFICATION
========================================= */

        boolean isTelebirrPayment =
                lowerMessage.contains(
                        "you have received"
                )
                        &&
                        lowerMessage.contains(
                                "by transaction number"
                        )
                        &&
                        lowerMessage.contains(
                                "to your telebirr account"
                        )
                        &&
                        lowerMessage.contains(
                                "thank you for using telebirr"
                        );


/* =========================================
   CBE PAYMENT NOTIFICATION
========================================= */

        boolean isCbePayment =
                lowerMessage.contains(
                        "you have received etb"
                )
                        &&
                        lowerMessage.contains(
                                "from account"
                        )
                        &&
                        lowerMessage.contains(
                                "to your account"
                        )
                        &&
                        lowerMessage.contains(
                                "thanks for banking with cbe"
                        );


        /*
         * Ignore every notification that is
         * not a Telebirr/CBE incoming payment.
         */

        if (
                !isTelebirrPayment &&
                        !isCbePayment
        ) {
            return;
        }


        String paymentMethod =
                isTelebirrPayment
                        ? "telebirr"
                        : "cbe";


        long currentTime =
                System.currentTimeMillis();


        Data inputData =
                new Data.Builder()

                        .putString(
                                "from",
                                sender
                        )

                        .putString(
                                "text",
                                normalizedMessage
                        )
                        .putString(
                                "paymentMethod",
                                paymentMethod
                        )

                        .putString(
                                "sentStamp",
                                String.valueOf(
                                        currentTime
                                )
                        )

                        .putString(
                                "receivedStamp",
                                String.valueOf(
                                        currentTime
                                )
                        )

                        .putString(
                                "sim",
                                "notification"
                        )

                        .putString(
                                "sourcePackage",
                                sbn.getPackageName()
                        )

                        .build();


        Constraints constraints =
                new Constraints.Builder()

                        .setRequiredNetworkType(
                                NetworkType.CONNECTED
                        )

                        .build();


        OneTimeWorkRequest request =
                new OneTimeWorkRequest.Builder(
                        PaymentForwardWorker.class
                )

                        .setInputData(
                                inputData
                        )

                        .setConstraints(
                                constraints
                        )

                        .build();


        WorkManager
                .getInstance(
                        getApplicationContext()
                )
                .enqueue(
                        request
                );

    }
}